In [1]:
import os
import shutil 
import librosa
import pandas as pd
from IPython.display import clear_output
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import soundfile as sf
from moviepy.audio.io.AudioFileClip import AudioFileClip

2025-03-14 18:13:59.212329: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-14 18:13:59.311307: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1741976039.345448    8830 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1741976039.355114    8830 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-14 18:13:59.427430: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [2]:
annotations__path = "IsoDataset/Ann/Chordlab"
lab_path = "IsoDatasetPro/Chordlab"
m4a_song_path = "IsoDataset/Songs/"
wav_song_path = "IsoDatasetPro/Songs/"
IsoDataset = "IsoDataset/"
IsoDatasetPro = "IsoDatasetPro/"
standardized_file = "IsoDatasetPro/Standardized"
chord_vocab_file = "IsoDatasetPro/chord_vocabulary_12_keys.csv"
combined_fpath = "IsoDatasetPro/CombinedData"


In [ ]:
# cOPIES the lab files from the IsoDataset/Ann/Chordlab directory to the IsoDatasetPro/Chordlab directory

available_annotations = []
# Loop through subdirectories in the Ann directory
for subdir in os.listdir(annotations__path):
    subdir_path = os.path.join(annotations__path, subdir)
    
    if os.path.isdir(subdir_path):  # Check if it's a directory
        # Create corresponding output subdirectory if it doesn't exist
        output_subdir = os.path.join(lab_path)
        os.makedirs(output_subdir, exist_ok=True)
        
        # Loop through files in the subdirectory
        for file in os.listdir(subdir_path):
            if file.endswith('.lab'):  # Check if the file is .lab
                input_lab_file = os.path.join(subdir_path, file)
                output_lab_file = os.path.join(output_subdir, f"{subdir}_{file[:2]}.lab")  # Corrected this line
                available_annotations.append(f"{subdir}_{file[:2]}")
                # Copy the .lab file to the new location
                shutil.copy(input_lab_file, output_lab_file)
                print(f"Copied {input_lab_file} to {output_lab_file}")

print(available_annotations)



Copied IsoDataset/Ann/Chordlab/01/01.lab to IsoDatasetPro/Chordlab/01_01.lab
Copied IsoDataset/Ann/Chordlab/01/02.lab to IsoDatasetPro/Chordlab/01_02.lab
Copied IsoDataset/Ann/Chordlab/01/03.lab to IsoDatasetPro/Chordlab/01_03.lab
Copied IsoDataset/Ann/Chordlab/01/04.lab to IsoDatasetPro/Chordlab/01_04.lab
Copied IsoDataset/Ann/Chordlab/01/05.lab to IsoDatasetPro/Chordlab/01_05.lab
Copied IsoDataset/Ann/Chordlab/01/06.lab to IsoDatasetPro/Chordlab/01_06.lab
Copied IsoDataset/Ann/Chordlab/01/07.lab to IsoDatasetPro/Chordlab/01_07.lab
Copied IsoDataset/Ann/Chordlab/01/08.lab to IsoDatasetPro/Chordlab/01_08.lab
Copied IsoDataset/Ann/Chordlab/01/09.lab to IsoDatasetPro/Chordlab/01_09.lab
Copied IsoDataset/Ann/Chordlab/01/10.lab to IsoDatasetPro/Chordlab/01_10.lab
Copied IsoDataset/Ann/Chordlab/01/11.lab to IsoDatasetPro/Chordlab/01_11.lab
Copied IsoDataset/Ann/Chordlab/01/12.lab to IsoDatasetPro/Chordlab/01_12.lab
Copied IsoDataset/Ann/Chordlab/01/13.lab to IsoDatasetPro/Chordlab/01_13.lab

KeyboardInterrupt: 

In [ ]:
# cONVERTS THE .m4a FILES TO .wav FILES


def convert_m4a_to_wav(m4a_song_path, wav_song_path):
    # Load the .m4a file using AudioFileClip
    audio_clip = AudioFileClip(m4a_song_path)
    
    # Write to .wav format
    audio_clip.write_audiofile(wav_song_path)

# Loop through subdirectories
for subdir in os.listdir(m4a_song_path):
    subdir_path = os.path.join(m4a_song_path, subdir)
    
    if os.path.isdir(subdir_path) :  # Check if it's a directory
        # Create corresponding output subdirectory if it doesn't exist
        output_subdir = os.path.join(wav_song_path)
        os.makedirs(output_subdir, exist_ok=True)
    
        # Loop through files in the subdirectory
        for file in os.listdir(subdir_path):
            if file.endswith('.m4a'):  # Check if the file is .m4a
                input_file = os.path.join(subdir_path, file)
                newfile = f"0{subdir}_{file.replace('.m4a', '')[:2]}.wav"
                output_file = os.path.join(output_subdir, newfile)

                # Convert and save the .m4a to .wav
                if newfile.removesuffix('.wav') in available_annotations:
                    convert_m4a_to_wav(input_file, output_file)
                    print(f"Converted {input_file} to {output_file}")
                else:
                    print(f"Skipping {input_file} as corresponding annotation not found")


MoviePy - Writing audio in IsoDatasetPro/Songs/01_01.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/01.m4a to IsoDatasetPro/Songs/01_01.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_02.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/02.m4a to IsoDatasetPro/Songs/01_02.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_03.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/03.m4a to IsoDatasetPro/Songs/01_03.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_04.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/04.m4a to IsoDatasetPro/Songs/01_04.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_05.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/05.m4a to IsoDatasetPro/Songs/01_05.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_06.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/06.m4a to IsoDatasetPro/Songs/01_06.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_07.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/07.m4a to IsoDatasetPro/Songs/01_07.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_08.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/08.m4a to IsoDatasetPro/Songs/01_08.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_09.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/09.m4a to IsoDatasetPro/Songs/01_09.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_10.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/10.m4a to IsoDatasetPro/Songs/01_10.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_11.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/11.m4a to IsoDatasetPro/Songs/01_11.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_12.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/12.m4a to IsoDatasetPro/Songs/01_12.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_13.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/13.m4a to IsoDatasetPro/Songs/01_13.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/01_14.wav


MoviePy - Done.
Converted IsoDataset/Songs/1/14.m4a to IsoDatasetPro/Songs/01_14.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_01.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/01.m4a to IsoDatasetPro/Songs/02_01.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_02.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/02.m4a to IsoDatasetPro/Songs/02_02.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_03.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/03.m4a to IsoDatasetPro/Songs/02_03.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_04.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/04.m4a to IsoDatasetPro/Songs/02_04.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_05.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/05.m4a to IsoDatasetPro/Songs/02_05.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_06.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/06.m4a to IsoDatasetPro/Songs/02_06.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_07.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/07.m4a to IsoDatasetPro/Songs/02_07.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_08.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/08.m4a to IsoDatasetPro/Songs/02_08.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_09.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/09.m4a to IsoDatasetPro/Songs/02_09.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_10.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/10.m4a to IsoDatasetPro/Songs/02_10.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_11.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/11.m4a to IsoDatasetPro/Songs/02_11.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_12.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/12.m4a to IsoDatasetPro/Songs/02_12.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_13.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/13.m4a to IsoDatasetPro/Songs/02_13.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/02_14.wav


MoviePy - Done.
Converted IsoDataset/Songs/2/14.m4a to IsoDatasetPro/Songs/02_14.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_01.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/01.m4a to IsoDatasetPro/Songs/03_01.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_02.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/02.m4a to IsoDatasetPro/Songs/03_02.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_03.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/03.m4a to IsoDatasetPro/Songs/03_03.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_04.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/04.m4a to IsoDatasetPro/Songs/03_04.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_05.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/05.m4a to IsoDatasetPro/Songs/03_05.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_06.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/06.m4a to IsoDatasetPro/Songs/03_06.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_07.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/07.m4a to IsoDatasetPro/Songs/03_07.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_08.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/08.m4a to IsoDatasetPro/Songs/03_08.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_09.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/09.m4a to IsoDatasetPro/Songs/03_09.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_10.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/10.m4a to IsoDatasetPro/Songs/03_10.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_11.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/11.m4a to IsoDatasetPro/Songs/03_11.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_12.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/12.m4a to IsoDatasetPro/Songs/03_12.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/03_13.wav


MoviePy - Done.
Converted IsoDataset/Songs/3/13.m4a to IsoDatasetPro/Songs/03_13.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_01.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/01 No Reply.m4a to IsoDatasetPro/Songs/04_01.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_02.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/02 I_m a Loser.m4a to IsoDatasetPro/Songs/04_02.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_03.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/03 Baby_s in Black.m4a to IsoDatasetPro/Songs/04_03.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_04.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/04 Rock and Roll Music.m4a to IsoDatasetPro/Songs/04_04.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_05.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/05 I_ll Follow the Sun.m4a to IsoDatasetPro/Songs/04_05.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_06.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/06 Mr. Moonlight.m4a to IsoDatasetPro/Songs/04_06.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_07.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/07 Medley_ Kansas City _ Hey.Hey.Hey.m4a to IsoDatasetPro/Songs/04_07.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_08.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/08 Eight Days a Week.m4a to IsoDatasetPro/Songs/04_08.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_09.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/09 Words of Love.m4a to IsoDatasetPro/Songs/04_09.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_10.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/10 Honey Don_t.m4a to IsoDatasetPro/Songs/04_10.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_11.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/11 Every Little Thing.m4a to IsoDatasetPro/Songs/04_11.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_12.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/12 I Don_t Want to Spoil the Party.m4a to IsoDatasetPro/Songs/04_12.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_13.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/13 What You_re Doing.m4a to IsoDatasetPro/Songs/04_13.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/04_14.wav


MoviePy - Done.
Converted IsoDataset/Songs/4/14 Everybody_s Trying to Be My Baby.m4a to IsoDatasetPro/Songs/04_14.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_01.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/01 Help!.m4a to IsoDatasetPro/Songs/05_01.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_02.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/02 The Night Before.m4a to IsoDatasetPro/Songs/05_02.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_03.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/03 You_ve Got to Hide Your Love Away.m4a to IsoDatasetPro/Songs/05_03.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_04.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/04 I Need You.m4a to IsoDatasetPro/Songs/05_04.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_05.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/05 Another Girl.m4a to IsoDatasetPro/Songs/05_05.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_06.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/06 You_re Going to Lose That Girl.m4a to IsoDatasetPro/Songs/05_06.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_07.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/07 Ticket to Ride.m4a to IsoDatasetPro/Songs/05_07.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_08.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/08 Act Naturally.m4a to IsoDatasetPro/Songs/05_08.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_09.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/09 It_s Only Love.m4a to IsoDatasetPro/Songs/05_09.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_10.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/10 You Like Me Too Much.m4a to IsoDatasetPro/Songs/05_10.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_11.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/11 Tell Me What You See.m4a to IsoDatasetPro/Songs/05_11.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_12.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/12 I_ve Just Seen a Face.m4a to IsoDatasetPro/Songs/05_12.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_13.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/13 Yesterday.m4a to IsoDatasetPro/Songs/05_13.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/05_14.wav


MoviePy - Done.
Converted IsoDataset/Songs/5/14 Dizzy Miss Lizzy.m4a to IsoDatasetPro/Songs/05_14.wav
Skipping IsoDataset/Songs/5/15 Help! (1965 stereo mix).m4a as corresponding annotation not found
Skipping IsoDataset/Songs/5/16 The Night Before (1965 stereo mix.m4a as corresponding annotation not found
Skipping IsoDataset/Songs/5/17 You_ve Got to Hide Your Love Away.m4a as corresponding annotation not found
Skipping IsoDataset/Songs/5/18 I Need You (1965 stereo mix).m4a as corresponding annotation not found
Skipping IsoDataset/Songs/5/19 Another Girl (1965 stereo mix).m4a as corresponding annotation not found
Skipping IsoDataset/Songs/5/20 You_re Going to Lose That Girl (1.m4a as corresponding annotation not found
Skipping IsoDataset/Songs/5/21 Ticket to Ride (1965 stereo mix).m4a as corresponding annotation not found
Skipping IsoDataset/Songs/5/22 Act Naturally (1965 stereo mix).m4a as corresponding annotation not found
Skipping IsoDataset/Songs/5/23 It_s Only Love (1965 stereo mix)

MoviePy - Done.
Converted IsoDataset/Songs/6/01 Drive My Car.m4a to IsoDatasetPro/Songs/06_01.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_02.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/02 Norwegian Wood (This Bird Has Flo.m4a to IsoDatasetPro/Songs/06_02.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_03.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/03 You Won_t See Me.m4a to IsoDatasetPro/Songs/06_03.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_04.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/04 Nowhere Man.m4a to IsoDatasetPro/Songs/06_04.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_05.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/05 Think for Yourself.m4a to IsoDatasetPro/Songs/06_05.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_06.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/06 The Word.m4a to IsoDatasetPro/Songs/06_06.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_07.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/07 Michelle.m4a to IsoDatasetPro/Songs/06_07.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_08.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/08 What Goes On.m4a to IsoDatasetPro/Songs/06_08.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_09.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/09 Girl.m4a to IsoDatasetPro/Songs/06_09.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_10.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/10 I_m Looking Through You.m4a to IsoDatasetPro/Songs/06_10.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_11.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/11 In My Life.m4a to IsoDatasetPro/Songs/06_11.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_12.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/12 Wait.m4a to IsoDatasetPro/Songs/06_12.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_13.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/13 If I Needed Someone.m4a to IsoDatasetPro/Songs/06_13.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/06_14.wav


MoviePy - Done.
Converted IsoDataset/Songs/6/14 Run for Your Life.m4a to IsoDatasetPro/Songs/06_14.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_01.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/01 Taxman.m4a to IsoDatasetPro/Songs/07_01.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_02.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/02 Eleanor Rigby.m4a to IsoDatasetPro/Songs/07_02.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_03.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/03 I_m Only Sleeping.m4a to IsoDatasetPro/Songs/07_03.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_04.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/04 Love You To.m4a to IsoDatasetPro/Songs/07_04.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_05.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/05 Here, There and Everywhere.m4a to IsoDatasetPro/Songs/07_05.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_06.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/06 Yellow Submarine.m4a to IsoDatasetPro/Songs/07_06.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_07.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/07 She Said She Said.m4a to IsoDatasetPro/Songs/07_07.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_08.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/08 Good Day Sunshine.m4a to IsoDatasetPro/Songs/07_08.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_09.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/09 And Your Bird Can Sing.m4a to IsoDatasetPro/Songs/07_09.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_10.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/10 For No One.m4a to IsoDatasetPro/Songs/07_10.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_11.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/11 Doctor Robert.m4a to IsoDatasetPro/Songs/07_11.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_12.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/12 I Want to Tell You.m4a to IsoDatasetPro/Songs/07_12.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_13.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/13 Got to Get You Into My Life.m4a to IsoDatasetPro/Songs/07_13.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/07_14.wav


MoviePy - Done.
Converted IsoDataset/Songs/7/14 Tomorrow Never Knows.m4a to IsoDatasetPro/Songs/07_14.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_01.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/01 Sgt. Pepper_s Lonely Hearts Club.m4a to IsoDatasetPro/Songs/08_01.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_02.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/02 With a Little Help From My Friend.m4a to IsoDatasetPro/Songs/08_02.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_03.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/03 Lucy in the Sky With Diamonds.m4a to IsoDatasetPro/Songs/08_03.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_04.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/04 Getting Better.m4a to IsoDatasetPro/Songs/08_04.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_05.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/05 Fixing a Hole.m4a to IsoDatasetPro/Songs/08_05.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_06.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/06 She_s Leaving Home.m4a to IsoDatasetPro/Songs/08_06.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_07.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/07 Being for the Benefit of Mr. Kite.m4a to IsoDatasetPro/Songs/08_07.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_08.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/08 Within You Without You.m4a to IsoDatasetPro/Songs/08_08.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_09.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/09 When I_m Sixty.Four.m4a to IsoDatasetPro/Songs/08_09.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_10.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/10 Lovely Rita.m4a to IsoDatasetPro/Songs/08_10.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_11.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/11 Good Morning Good Morning.m4a to IsoDatasetPro/Songs/08_11.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_12.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/12 Sgt. Pepper_s Lonely Hearts Club.m4a to IsoDatasetPro/Songs/08_12.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/08_13.wav


MoviePy - Done.
Converted IsoDataset/Songs/8/13 A Day in the Life.m4a to IsoDatasetPro/Songs/08_13.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/09_01.wav


MoviePy - Done.
Converted IsoDataset/Songs/9/01 Magical Mystery Tour.m4a to IsoDatasetPro/Songs/09_01.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/09_02.wav


MoviePy - Done.
Converted IsoDataset/Songs/9/02 The Fool on the Hill.m4a to IsoDatasetPro/Songs/09_02.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/09_03.wav


MoviePy - Done.
Converted IsoDataset/Songs/9/03 Flying.m4a to IsoDatasetPro/Songs/09_03.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/09_04.wav


MoviePy - Done.
Converted IsoDataset/Songs/9/04 Blue Jay Way.m4a to IsoDatasetPro/Songs/09_04.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/09_05.wav


MoviePy - Done.
Converted IsoDataset/Songs/9/05 Your Mother Should Know.m4a to IsoDatasetPro/Songs/09_05.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/09_06.wav


MoviePy - Done.
Converted IsoDataset/Songs/9/06 I Am the Walrus.m4a to IsoDatasetPro/Songs/09_06.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/09_07.wav


MoviePy - Done.
Converted IsoDataset/Songs/9/07 Hello Goodbye.m4a to IsoDatasetPro/Songs/09_07.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/09_08.wav


MoviePy - Done.
Converted IsoDataset/Songs/9/08 Strawberry Fields Forever.m4a to IsoDatasetPro/Songs/09_08.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/09_09.wav


MoviePy - Done.
Converted IsoDataset/Songs/9/09 Penny Lane.m4a to IsoDatasetPro/Songs/09_09.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/09_10.wav


MoviePy - Done.
Converted IsoDataset/Songs/9/10 Baby You_re a Rich Man.m4a to IsoDatasetPro/Songs/09_10.wav
MoviePy - Writing audio in IsoDatasetPro/Songs/09_11.wav


MoviePy - Done.
Converted IsoDataset/Songs/9/11 All You Need Is Love.m4a to IsoDatasetPro/Songs/09_11.wav


In [ ]:
# Function to extract chroma features from an audio file
# Returns a tuple of the chroma features and the sample rate

#STFT
def extract_chroma_features(audio_file_path, sr=22050, hop_length=512):
    # Load the audio file
    y, sr = librosa.load(audio_file_path, sr=sr)
    
    # Extract chroma features (12 bins per octave)
    chroma = librosa.feature.chroma_stft(y=y, sr=sr, hop_length=hop_length)
    
    # Optionally, normalize the chroma features
    chroma = librosa.util.normalize(chroma)
    
    return chroma, sr


#CQT
def extract_features(audio_file_path):
    y, sr = librosa.load(audio_file_path, sr=22050)
    chroma = librosa.feature.chroma_cqt(y=y, sr=sr, hop_length=2048)  # Chroma representation
    time_steps = librosa.times_like(chroma[0], sr=sr)  # Get time axis for spectrogram
    return chroma, time_steps


In [ ]:
# Loop through all the .wav files in the subdirectory
for audio_file in os.listdir(wav_song_path):
    audio_file_path = os.path.join(wav_song_path, audio_file)
    print(f"Processing {audio_file_path}")
    # List all .wav files in the subdirectory
    audio_files = [f for f in wav_song_path if f.endswith('.wav')]

    # Extract chroma features
    chroma, sr = extract_chroma_features(audio_file_path)

    # Plotting the chroma features
    plt.figure(figsize=(10, 6))
    librosa.display.specshow(chroma, x_axis='time', y_axis='chroma', sr=sr)
    plt.colorbar(label='Chroma Magnitude')
    plt.title(f'Chroma Feature Plot: {audio_file}')
    plt.show()
    clear_output(wait=True)


Processing IsoDatasetPro/Songs/03_07.wav


KeyboardInterrupt: 

In [ ]:

# Function to load .lab file
def load_lab_file(lab_path):
    df = pd.read_csv(lab_path, sep='\s+', header=None, names=["start", "end", "chord"])
    return df

# Function to align labels
def align_labels(time_steps, annotations):
    labels = []
    for t in time_steps:
        chord = "N"  # Default to 'N' (No chord)
        for _, row in annotations.iterrows():
            if row["start"] <= t < row["end"]:
                chord = row["chord"]
                break
        labels.append(chord)
    return np.array(labels)


In [83]:
# CONVERTING CHORDS TO CHROMA FEATURES

chroma_data = {}  # Store chroma features with file names as keys

# Loop through Songs
if os.path.isdir(wav_song_path):  # Ensure it's a directory
    for file in os.listdir(wav_song_path):
        if file.endswith('.wav'):
            print(f"Extracting chroma for {file}...")
            audio_file_path = os.path.join(wav_song_path, file)
            chroma, time_steps = extract_features(audio_file_path)  # Extract chroma

            chroma_data[file.replace('.wav', '')] = (chroma, time_steps)  # Store without extension
            print(chroma)
            print(f"Extracted chroma for {file}, shape: {chroma.shape}")
print(chroma_data)


Extracting chroma for 01_01.wav...
[[0.04538263 0.05134265 0.06366851 ... 0.3410173  0.33348945 0.32618257]
 [0.04711983 0.02166085 0.06259377 ... 0.39121738 0.39476305 0.40176448]
 [0.04947691 0.03616705 0.04063065 ... 0.3255211  0.33676934 0.34744832]
 ...
 [0.38862056 0.35292405 0.3398232  ... 0.37265685 0.37824684 0.38989967]
 [0.07800984 0.04858889 0.04958978 ... 0.38420302 0.38794923 0.39305538]
 [0.07939743 0.0718535  0.04996305 ... 0.34525397 0.3353646  0.32198972]]
Extracted chroma for 01_01.wav, shape: (12, 7669)
Extracting chroma for 01_02.wav...
[[0.29594854 0.37714595 0.55513793 ... 0.42649043 0.40700758 0.40501264]
 [0.42427143 0.46117443 0.5693155  ... 0.367619   0.34716773 0.3436009 ]
 [0.46846327 0.43605885 0.53201556 ... 0.54342955 0.5261195  0.52436674]
 ...
 [0.28786492 0.37098512 0.4498488  ... 0.4466817  0.43736863 0.43684322]
 [0.24535124 0.43588683 0.57310724 ... 0.35896996 0.33853796 0.3283771 ]
 [0.27832818 0.47314724 0.69168377 ... 0.3796849  0.3465858  0.328

KeyboardInterrupt: 

In [ ]:
# LOAD CHORD LABELS

chord_labels_data = {}  # Store chord labels with file names as keys

# Loop through Chordlab
if os.path.isdir(lab_path):  # Ensure it's a directory
    for file in os.listdir(lab_path):
        if file.endswith('.lab'):
            lab_file_path = os.path.join(lab_path, file)
            annotations = load_lab_file(lab_file_path)  # Load chord labels

            chord_labels_data[file.replace('.lab', '')] = annotations  # Store without extension

            print(f"Loaded chord labels for {file}")
print(chord_labels_data)


Loaded chord labels for 01_01.lab
Loaded chord labels for 01_02.lab
Loaded chord labels for 01_03.lab
Loaded chord labels for 01_04.lab
Loaded chord labels for 01_05.lab
Loaded chord labels for 01_06.lab
Loaded chord labels for 01_07.lab
Loaded chord labels for 01_08.lab
Loaded chord labels for 01_09.lab
Loaded chord labels for 01_10.lab
Loaded chord labels for 01_11.lab
Loaded chord labels for 01_12.lab
Loaded chord labels for 01_13.lab
Loaded chord labels for 01_14.lab
Loaded chord labels for 02_01.lab
Loaded chord labels for 02_02.lab
Loaded chord labels for 02_03.lab
Loaded chord labels for 02_04.lab
Loaded chord labels for 02_05.lab
Loaded chord labels for 02_06.lab
Loaded chord labels for 02_07.lab
Loaded chord labels for 02_08.lab
Loaded chord labels for 02_09.lab
Loaded chord labels for 02_10.lab
Loaded chord labels for 02_11.lab
Loaded chord labels for 02_12.lab
Loaded chord labels for 02_13.lab
Loaded chord labels for 02_14.lab
Loaded chord labels for 03_01.lab
Loaded chord l

In [ ]:
# COMBINE CHROMA AND CHORD LABELS

combined_data = {}  # Store combined data
print(chroma_data.keys())
for key in chroma_data.keys():
    if key in chord_labels_data:  # Check if matching lab file exists
        print(key)
        chroma, time_steps = chroma_data[key]
        annotations = chord_labels_data[key]

        chord_labels = align_labels(time_steps, annotations)  # Align chord labels

        combined_data[key] = (chroma, chord_labels)  # Store final processed data

        print(f"Combined data for {key}: Chroma shape: {chroma.shape}, Chords: {chord_labels[:10]}")

       # Define the directory to save CSV files
        csv_save_dir = "IsoDatasetPro/CombinedData"
        os.makedirs(csv_save_dir, exist_ok=True)

        for key, (chroma, chord_labels) in combined_data.items():
            # Transpose chroma so that time steps are rows
            chroma = chroma.T  # Now shape (N, 12), matching chord_labels (N,)

            # Convert to DataFrame
            df = pd.DataFrame(chroma, columns=[f"Chroma_{i}" for i in range(12)])

            # Add chord labels
            df["Chord_Label"] = chord_labels

        # Save to CSV
        save_path = os.path.join(csv_save_dir, f"{key}.csv")
        df.to_csv(save_path, index=False)

        print(f"Saved combined data for {key} at {save_path}")


    else:
        print(f"Warning: No chord labels found for {key}")


dict_keys(['01_01', '01_02', '01_03', '01_04', '01_05', '01_06', '01_07', '01_08', '01_09', '01_10', '01_11', '01_12', '01_13', '01_14', '02_01', '02_02', '02_03', '02_04', '02_05', '02_06', '02_07', '02_08', '02_09', '02_10', '02_11', '02_12', '02_13', '02_14', '03_01', '03_02', '03_03', '03_04', '03_05', '03_06', '03_07', '03_08', '03_09', '03_10', '03_11', '03_12', '03_13', '04_01', '04_02', '04_03', '04_04', '04_05', '04_06', '04_07', '04_08', '04_09', '04_10', '04_11', '04_12', '04_13', '04_14', '05_01', '05_02', '05_03', '05_04', '05_05', '05_06', '05_07', '05_08', '05_09', '05_10', '05_11', '05_12', '05_13', '05_14', '06_01', '06_02', '06_03', '06_04', '06_05', '06_06', '06_07', '06_08', '06_09', '06_10', '06_11', '06_12', '06_13', '06_14', '07_01', '07_02', '07_03', '07_04', '07_05', '07_06', '07_07', '07_08', '07_09', '07_10', '07_11', '07_12', '07_13', '07_14', '08_01', '08_02', '08_03', '08_04', '08_05', '08_06', '08_07', '08_08', '08_09', '08_10', '08_11', '08_12', '08_13',

In [18]:
# Define categories (merging 'X' into 'N')
roots = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'N', 'X']
basses = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'N', 'X']
triads = ['Major', 'Minor', 'Diminished', 'Augmented', 'Sus2', 'Sus4', 'N', 'X']
fourths = ['dim7', 'min7', 'maj7', 'maj6', 'N', 'X']

# Mapping flats to sharps (for example 'Db' -> 'C#', 'Eb' -> 'D#', etc.)
flat_to_sharp_mapping = {
    'Db': 'C#', 'Eb': 'D#', 'Fb': 'E', 'Gb': 'F#', 'Ab': 'G#', 'Bb': 'A#', 'Cb': 'B', 'Fb': 'E', 'B#': 'C', 'E#': 'F'
}

In [19]:
# STANDARD CHORDS

standard_chords_file = "IsoDatasetPro/standard_chords.csv"
os.makedirs(standardized_file, exist_ok=True)

# Load the standard chords mapping
standard_df = pd.read_csv(standard_chords_file)
chord_mapping = dict(zip(standard_df['chord'], standard_df['standardized_label']))

# Function to replace flats with sharps in chord names
def replace_flats_in_chord(chord):
    for flat, sharp in flat_to_sharp_mapping.items():
        chord = chord.replace(flat, sharp)
    return chord

# Loop through each sample file in the directory
for file in os.listdir(combined_fpath):
    if file.endswith(".csv"):  # Ensure only CSV files are processed
        print(f"Processing sample: {file}")
        
        combined_file = os.path.join(combined_fpath, file)
        
        if os.path.exists(combined_file):
            df = pd.read_csv(combined_file)

            print("Before standard replacement:")
            print(df['Chord_Label'].unique())

            # Replace incorrect labels with correct ones
            df.replace({'Chord_Label': chord_mapping}, inplace=True)

            print("After standard replacement:")
            print(df['Chord_Label'].unique())

            # Now apply flat to sharp replacement for each chord label
            df['Chord_Label'] = df['Chord_Label'].apply(replace_flats_in_chord)

            print("After replacing flats with sharps:")
            print(df['Chord_Label'].unique())
            
            # Save the corrected file
            save_path = os.path.join(standardized_file, file)
            df.to_csv(save_path, index=False)
            print(f"Updated: {file}")

print("Processing complete!")


Processing sample: 01_01.csv
Before standard replacement:
['N' 'E' 'A' 'B' 'E:7/3' 'A:min/b3' 'E:9']
After standard replacement:
['N' 'E:maj' 'A:maj' 'B:maj' 'E:7/3' 'A:min/b3' 'E:7']
After replacing flats with sharps:
['N' 'E:maj' 'A:maj' 'B:maj' 'E:7/3' 'A:min/b3' 'E:7']
Updated: 01_01.csv
Processing sample: 01_02.csv
Before standard replacement:
['N' 'F' 'G' 'C' 'A:min']
After standard replacement:
['N' 'F:maj' 'G:maj' 'C:maj' 'A:min']
After replacing flats with sharps:
['N' 'F:maj' 'G:maj' 'C:maj' 'A:min']
Updated: 01_02.csv
Processing sample: 01_03.csv
Before standard replacement:
['N' 'D' 'B:min' 'E:min' 'A' 'D/2' 'D/3' 'G' 'E:7' 'G:min']
After standard replacement:
['N' 'D:maj' 'B:min' 'E:min' 'A:maj' 'D:sus2' 'D:maj/3' 'G:maj' 'E:7'
 'G:min']
After replacing flats with sharps:
['N' 'D:maj' 'B:min' 'E:min' 'A:maj' 'D:sus2' 'D:maj/3' 'G:maj' 'E:7'
 'G:min']
Updated: 01_03.csv
Processing sample: 01_04.csv
Before standard replacement:
['N' 'Bb' 'Eb:7' 'F:9' 'Eb:9' 'F' 'Bb:7' 'Eb' '

In [3]:
# Dataset Expansion
exp_song_path = "IsoDatasetPro/Expanded/Songs"
exp_file_path = "IsoDatasetPro/Expanded/Files"

scale = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']


In [34]:
# DATA AUGMENTATION

# Function to shift pitch of an audio file
def pitch_shift_audio(audio_file_path, shift_steps):
    for file in os.listdir(audio_file_path):
        if file.endswith('.wav'):
            file_path = os.path.join(audio_file_path, file)
            file_name = file.split('.')[0]
            # Load the audio file
            y, sr = librosa.load(file_path, sr=22050, mono=True)

            for i in range(-shift_steps, shift_steps + 1):
                # Pitch shift by i semitones
                y_shifted = librosa.effects.pitch_shift(y=y, sr=sr, n_steps=i)

                # Save the shifted audio to a new file
                save_path = os.path.join(exp_song_path, f"{file_name}_({i}).wav")
                sf.write(save_path, y_shifted, sr)
                print(f"Saved {save_path}")

# Function to shift pitch of chord labels
def shift_chord(chord, semitone_shift):
    if (chord == 'N' or chord == 'X'or semitone_shift == 0):
        return chord
    else:
        root = chord.split(':')[0]  # Extract root note (like 'C', 'G', 'D#')
        quality = chord.split(':')[1] 

        # Find the current index of the root note
        root_idx = scale.index(root)

        # Shift the root note by `i` semitones
        new_root = scale[(root_idx + semitone_shift) % 12]

        # Return the shifted chord
        # print(f'{root}:{quality} -> {new_root}:{quality}')
        return f'{new_root}:{quality}'

# Function to shift pitch of chord labels in CSV files
def pitch_shift_files(csv_file_path, song_path, shift_steps):
    print(csv_file_path)
    for file in os.listdir(csv_file_path):
        print(f"Processing {file}")
        if file.endswith('.csv'):
            file_path = os.path.join(csv_file_path, file)
            file_name = file.split('.')[0]

            for i in range(-shift_steps, shift_steps + 1):
                df = pd.read_csv(file_path)
                # Shift the chord labels by i semitones
                df['Chord_Label'] = df['Chord_Label'].apply(lambda x: shift_chord(x, i))
                new_file = f"{file_name}_({i}).csv"
                print(f"Processing:{new_file}")
                
                song = song_path + '/' + new_file.replace('.csv', '.wav')
                print(f"Processing:{song}")
                chroma, sr = extract_features(song)

                # Calculate timestamp for each frame (hop_length = 512)
                hop_length = 512
                timestamps = np.arange(chroma.T.shape[0]) * hop_length / 22050
                timestamps = np.round(timestamps, 4)

                # Replace the first 12 columns with new chroma data
                newdf = pd.DataFrame(chroma.T, columns=[f"Chroma_{i}" for i in range(12)])
                newdf["Chord_Label"] = df["Chord_Label"]
                newdf["Timestamp"] = timestamps
                df = newdf
                print(df)

                # Save the shifted data to a new file
                save_path = os.path.join(exp_file_path, f"{file_name}_({i}).csv")
                df.to_csv(save_path, index=False)
                print(f"Saved {save_path}\n")


In [5]:
pitch_shift_audio(wav_song_path, 3)


Saved IsoDatasetPro/Expanded/Songs/01_01_(-3).wav
Saved IsoDatasetPro/Expanded/Songs/01_01_(-2).wav
Saved IsoDatasetPro/Expanded/Songs/01_01_(-1).wav
Saved IsoDatasetPro/Expanded/Songs/01_01_(0).wav
Saved IsoDatasetPro/Expanded/Songs/01_01_(1).wav
Saved IsoDatasetPro/Expanded/Songs/01_01_(2).wav
Saved IsoDatasetPro/Expanded/Songs/01_01_(3).wav
Saved IsoDatasetPro/Expanded/Songs/01_02_(-3).wav
Saved IsoDatasetPro/Expanded/Songs/01_02_(-2).wav
Saved IsoDatasetPro/Expanded/Songs/01_02_(-1).wav
Saved IsoDatasetPro/Expanded/Songs/01_02_(0).wav
Saved IsoDatasetPro/Expanded/Songs/01_02_(1).wav
Saved IsoDatasetPro/Expanded/Songs/01_02_(2).wav
Saved IsoDatasetPro/Expanded/Songs/01_02_(3).wav
Saved IsoDatasetPro/Expanded/Songs/01_03_(-3).wav
Saved IsoDatasetPro/Expanded/Songs/01_03_(-2).wav
Saved IsoDatasetPro/Expanded/Songs/01_03_(-1).wav
Saved IsoDatasetPro/Expanded/Songs/01_03_(0).wav
Saved IsoDatasetPro/Expanded/Songs/01_03_(1).wav
Saved IsoDatasetPro/Expanded/Songs/01_03_(2).wav
Saved IsoDa

In [35]:
pitch_shift_files(standardized_file, exp_song_path, 3)
print("Processing complete!")

IsoDatasetPro/Standardized
Processing 01_01.csv
Processing:01_01_(-3).csv
Processing:IsoDatasetPro/Expanded/Songs/01_01_(-3).wav
      Chroma_0  Chroma_1  Chroma_2  Chroma_3  Chroma_4  Chroma_5  Chroma_6  \
0     0.157479  0.105600  0.306396  1.000000  0.406680  0.968817  0.940406   
1     0.134352  0.088719  0.227232  0.973409  0.339904  1.000000  0.918482   
2     0.116891  0.122308  0.208164  0.884368  0.307603  1.000000  0.853475   
3     0.094171  0.145007  0.272641  0.768441  0.315389  1.000000  0.835133   
4     0.093605  0.145980  0.340790  0.730570  0.341387  1.000000  0.843078   
...        ...       ...       ...       ...       ...       ...       ...   
7664  0.241030  0.290868  0.207455  0.294067  1.000000  0.749886  0.293228   
7665  0.244141  0.288424  0.208721  0.312156  1.000000  0.748203  0.290860   
7666  0.263740  0.294629  0.203800  0.313105  1.000000  0.752622  0.299532   
7667  0.272453  0.292368  0.204347  0.303911  1.000000  0.760240  0.308614   
7668  0.27670